### DISCUSSION TITLE
Documentation for ESPHome with BTHome

### DISCUSSION THREAD

**Discussion by nikosch86** [rbaron/b-parasite#157] [General]
I would like to try and use ESPHome as a proxy as @rbaron mentioned in some of the issues in the tracker here.
I have seen the b_parasite component and that works fine, is there support for parasites with bthome v2 and how would the config file for esphome look like to make it work?

Thanks!

**Comment by nikosch86** [comment]
Nevermind, it was just confusing that there is no log output or any indication that it is already working from esphome.  
In fact it works transparently with very minimal config, just a network connection and this:  
```
# Enable Home Assistant API
api:
  password: "ReplaceThisString"
  
esp32_ble_tracker:
  scan_parameters:
    active: true

bluetooth_proxy:
  active: true
  ```

On the Home Assistant side the ESPHome Integration has to be added (Settings > Add Integration > ESPHome).  
The ESPHome device should have a hostname or static IP (I am using DHCP Static Mappings for this)  
Connect to it using the hostname and the password set earelier.  
The BTHome Devices will populate as the ESPHome receives the BLE Advertisements.
