### ISSUE TITLE
Kitspace.yaml update

### ISSUE THREAD

**Issue by nyok92** [rbaron/b-parasite#125]
HI @rbaron ,
It seems that kispace has not been updated with lastest revision of b-parasite.
Could you maybe updte the kitspace.yaml according to their standard? or re-run the integration in their repo ?
It could help many to order and choose from different PCB Builders/assemblers.
Thanks

```
summary: an open source soil moisture and ambient temperature/humidity/light sensor.

site: https://github.com/rbaron/b-parasite

color: green

bom: kicad/parasite.csv ## maybe add the 1-click .tsv file instead

gerbers: kicad/gerber

eda:
  type: kicad
  pcb: kicad/parasite.kicad_pcb
```
